### ISSUE TITLE
Clean up of DateTime expiration

### ISSUE THREAD

**Issue by AndrewCarterUK** [php-cache/adapter-common#11]
Having a look at the [CacheItem](https://github.com/php-cache/adapter-common/blob/master/src/CacheItem.php) implementation.

The type hint on the `getExpiration` method should probably be `DateTimeInterface` (on `CacheItem` and `HasExpirationDateInterface`) as I believe the constructor allows these objects.

Also, all date time objects should be immediately cloned once they have been passed to `__construct` or `expiresAt`. Otherwise later changes to the object will change the expiration of the cache item.

**Comment by Nyholm** [comment]
Awesome. Thank you for the feedback!

**Comment by AndrewCarterUK** [comment]
No worries, I was going to suggest adding tests for the cloning bug - but it's pretty impossible to make it generic seeing as the method isn't on the specification.

Well done on this implementation though guys - it all looks very clean (which is quite impressive given the specification)!

**Comment by Nyholm** [comment]
For future reference: The bug was fixed here https://github.com/php-cache/adapter-common/commit/aec9549607076ed12825823b099c45130edce780 but no test were added. This issue can be closed once the tests are in place.
