### ISSUE TITLE
About isHit()

### ISSUE THREAD

**Issue by Nyholm** [php-cache/adapter-common#7]
About the isHit() discussion, I found this on the [mailing list](https://groups.google.com/forum/#!topic/php-fig/pxy_VYgm2sU).

Larry Garfield: 
>  isHit() is whether or not the cache lookup was a hit; it has no relation to changes to the object after that. 

Which means that our isHit() function does not have to check for the expiration date. It would mean that isHit could look like this: 

```php
public function isHit()
{
    return $this->hasValue;
}
```

**Comment by aequasi** [comment]
Whether or not the cache lookup is a hit is dependant on the expiration
date though. It depends on the cache adapter really.

A. Scherer

**Comment by Nyholm** [comment]
Okey. Good.
